src/api/product/content-types/item/schema.json
src/components/product/needs-met.json
types/generated/components.d.ts
types/generated/contentTypes.d.ts

Closes #15 
Adds a `Product.NeedsMet` component to the `Product.Item` content type in the Strapi CMS
Have a couple questions: 
1. Re the `Type` field: Are `DA` and `SPHERE` the only options?
2. What does `DA` stand for? Should we use the full name instead of `DA`?
3. Plain text is ok for the `Notes` field?

Add Product.NeedsMet component to Product.Item content type

---

src/api/product/content-types/item/schema.json
src/components/product/value.json
types/generated/components.d.ts
types/generated/contentTypes.d.ts

Resolves #12 
Note: the PricePerUnit field should be replaced with a computed value (something like a view in SQL) but to the extent that I could find this does not appear to be supported by strapi at this time.

Feat(data-modelling): Create product.Value component

---

src/api/needs-assessment/content-types/survey/schema.json
src/api/needs-assessment/controllers/survey.ts
src/api/needs-assessment/routes/survey.ts
src/api/needs-assessment/services/survey.ts
types/generated/contentTypes.d.ts

Resolves #46
Creates Assessment.Survey collection type

feat(data-modeling): Create Assessment.Survey collection type 

---

src/api/needs-assessment/content-types/need/schema.json
src/api/needs-assessment/content-types/survey/schema.json
src/api/needs-assessment/controllers/need.ts
src/api/needs-assessment/routes/need.ts
src/api/needs-assessment/services/need.ts
types/generated/contentTypes.d.ts

Resolves #44 
Creates NeedsAssessment.Need collection type for the needs data.
_**Note**_: There is not an option to have a relation field type as "required" in the Strapi admin currently, therefore all relations for this collection exist as inputs that are not required.

feat(data-modeling): Create NeedsAssessment.Need collection type

---

src/api/product/controllers/item.ts
src/extensions/content-manager/strapi-server.ts
src/functions/content-types/index.ts
src/functions/content-types/product/item.ts

Closes: #49 
Adds functions that allow us to calculate the values of content-type and component fields based on the values of other fields during the data entry process. Works with data entry from either the API or the Admin Panel (Content Manager). 
Specific calculations are implemented for fields in the `Product.info`'s `volume` and `weight` components.

feat: add functionality to perform custom calculations on data entry 

---

README.md

Fixes #54 
This PR adds a new section to the README file that provides instructions for setting up a Gitpod development environment for the project. 
<br/>
<br/>

doc: add gitpod setup to the readme

---

src/components/product/needs-met.json
src/components/product/value.json
src/components/product/volume.json
src/components/product/weight.json
src/extensions/documentation/documentation/1.0.0/full_documentation.json
src/functions/content-types/product/item.ts
types/generated/components.d.ts

Updates the `Product.info` components' field names to be more consistent and/or clarify their intent.
Also removes the default values in the `weight` component.
Closes #63

Fix: update Product.item components

---

src/functions/content-types/index.ts

Fixes bug where any Content-type other than `Product.item` created or updated via the Admin Panel was saved with empty field values. Thanks @ll-zerr for finding that! 
Closes #72

fix: restore create/update for all content-types via Admin Panel

---

src/api/product/controllers/item.ts

The `Product.item` controller now calls its calculation function directly. Detecting the content-type (as is done in the Admin panel extension) is not necessary here. We already know the content-type since we're in the specific controller for it.

refactor `Product.item` controller 

---

src/functions/content-types/index.ts

Forgot to remove the API path option from the `contentTypeHandlers` object. We no longer need to detect requests coming from the API in the `processContentType` function.

refactor: remove code that is no longer needed

---

src/functions/content-types/product/item.ts

Adds a calculation for the `monthlyNeedsMetPerItem` field in the `Product.item/needsMet` component
Adds a calculation for the `pricePerItemUSD` field in the `Product.item/value` component. 
Followup to #64

Add monthlyNeedsMet and pricePerItemCalculations

---

.yarnrc.yml

I'm configuring Yarn to explicitly support specific OSes and CPU architectures. This is to hopefully solve an issue one of our devs is experiencing with missing architecture files for the Sharp library.
This is based on the [recommendations from the Sharp library](https://sharp.pixelplumbing.com/install#cross-platform) and the [Yarn docs](https://yarnpkg.com/configuration/yarnrc#supportedArchitectures).
1. Switch to this branch.
2. Remove the `node_modules` directory.
3. Run `yarn`.
4. Run `yarn run develop`.

[CHORE] Trying to explicitly support different OSes and CPU architectures

---

jest.config.mjs
package.json
src/functions/content-types/product/item.test.ts
tests/app.test.ts

Adds tests for the custom calculations in the `Product.Info` content-type. 
Also includes a few jest config changes. 
Part of #145 
1. Run `yarn test`  (may need to run `yarn test:with-build` the first time if the `strapi is defined` test fails)
2. Confirm all tests pass.

test: add tests for `Product.Item` calculations

---

src/api/group/controllers/group.ts
src/api/product/controllers/item.ts
src/api/reporting/controllers/cargo.ts

Fix for https://github.com/distributeaid/aggregated-public-information/issues/182
Locally, run `yarn tsc` (or `yarn run check:types`) and make sure there are no errors. On GitHub, open a PR and ensure the pipeline continues past the `Run type check` step.

fix: remove @ts-expect-error directives causing ci/cd error

---

.github/FUNDING.yml

Removed link to Open Collective Foundation in `FUNDING.yml` per https://github.com/distributeaid/aggregated-public-information/issues/180.
Go to [the repo](https://github.com/distributeaid/aggregated-public-information) and make sure the sponsorship information looks correct.

docs: remove Open Collective Foundation link

---

src/scripts/import-needs-assessment-data/add-categories.ts
src/scripts/import-needs-assessment-data/add-items.ts
src/scripts/import-needs-assessment-data/index.ts

- Responding to guel-codes comments on this pull request.
- Simplified logic in chaining .then() function calls.
- Simplified logic for populating resultsMap. 
- Ran auto format checker.
[Link to Pull Request and review](https://github.com/distributeaid/aggregated-public-information/pull/210)
Add the attached [needs-data.json](https://github.com/user-attachments/files/17951499/needs-data.json) file to the src/scripts/import-needs-assessment-data folder, setup the src/scripts/.env file. Rename needs-data.json to needs-data.json(1) or change target filename in src/scripts/import-needs-assessment-data/index.ts.
Create dummy API key for local Strapi instance and use for STRAPI_API_KEY= in .env.
Comment out existing console.log() calls in index.ts. Uncomment and isolate addCategories function …

Pr 210 review

---

src/api/needs-assessment/content-types/survey/schema.json
src/api/needs-assessment/controllers/survey.ts
src/functions/content-types/index.ts
src/functions/content-types/needs-assessment/survey.test.ts
src/functions/content-types/needs-assessment/survey.ts
types/generated/contentTypes.d.ts

Added `yearQuarter` field to `NeedsAssessment.Survey` per https://github.com/distributeaid/aggregated-public-information/issues/191
Making this a draft until testing is more fleshed out

feat: added `yearQuarter` field to `NeedsAssessment.Survey`

---

src/api/product/content-types/item/schema.json
src/scripts/import-needs-assessment-data/add-categories.ts
src/scripts/import-needs-assessment-data/add-items.ts
src/scripts/import-needs-assessment-data/index.ts
src/scripts/import-needs-assessment-data/types.d.ts
types/generated/contentTypes.d.ts

This pull request currently populates the `name` field type for the `Product.Category` collection. It relates to task 1 in PR #112. This collection still requires the `items` relation field type to be populated.
Still to do in this PR:
**_**Update:_** This pull request now populates the `Product.Category` and `Product.Item` collections.
Add the attached [needs-data.json](https://github.com/user-attachments/files/17951499/needs-data.json) file to the `src/scripts/import-needs-assessment-data` folder, setup the `src/scripts/.env` file, then run the dev server in one terminal and `yarn script:import-needs-assessment-data` in another. The logs should show you that 11 categories and 290 products have been created successfully or already exist. (The json file was updated with the full dataset …

feat(data-ingestion): Upload product items from the needs data to the Strapi collection

---

src/scripts/import-needs-assessment-data/add-regions.ts
src/scripts/import-needs-assessment-data/add-subregions.ts

1. The upload function in `add-regions.ts` and `add-subregions.ts` is updated to reflect the lowercase lettering requirement for the name property in each Strapi collection.
Resolves [Issue #346](https://github.com/distributeaid/aggregated-public-information/issues/346) 
1. Add the following [needs-data.json](https://github.com/user-attachments/files/20471441/needs-data.json) file to the `src/scripts/import-needs-assessment-data` folder
2. Create an API key in the Strapi console for testing this feature
3. Set up the `src/scripts/.env` file using the `.env.example` template and add your Strapi API key
4. Run the dev server in one terminal and `yarn script:import-needs-assessment-data` in another
You should now see the data results for: 
- Geo.regions indicate that 6 regions have been …

Fix(data-ingestion): Update upload function for region and subregion 

---

src/scripts/import-needs-assessment-data/add-needs.ts
src/scripts/import-needs-assessment-data/index.ts
yarn.lock

This pull request adds a function to view the workflow status of the historic needs data processing during data transfer of the needs to the NeedsAssessment.Need collection. It resolves [#297](https://github.com/distributeaid/aggregated-public-information/issues/297).
Note: The region counts and duplicate details have been left for viewing to monitor the accuracy of data processing at this stage.
1. Add the following [needs-data.json](https://github.com/user-attachments/files/20579847/needs-data.json) file to the `src/scripts/import-needs-assessment-data` folder
2. Create an API key in the Strapi console for testing this feature
3. Set up the `src/scripts/.env` file using the `src/scripts/.env.example` template and add your Strapi API key
4. Run the dev server in one terminal and `yarn …

feat(data-ingestion): Add a function for workflow status of needs data
